const reasons = [
  "Your smile brightens my day.",
  "You always know how to make me laugh.",
  "Your kindness inspires me.",
  "You listen to me with genuine interest.",
  "You support my dreams.",
  "You have the most beautiful eyes.",
  "You make me feel safe.",
  "Your hugs are the best.",
  "You are incredibly thoughtful.",
  "You bring out the best in me.",
  "You're my best friend.",
  "You accept me as I am.",
  "Your love for adventure.",
  "The way you care about me.",
  "Your creativity amazes me.",
  "You make even the ordinary moments special.",
  "Your sense of humor.",
  "The way you look at me.",
  "You are so patient.",
  "You never give up on us.",
  "You are my biggest cheerleader.",
  "Your intelligence.",
  "You're a great cook.",
  "You're my confidant.",
  "You surprise me in the best ways.",
  "You're always up for trying new things.",
  "Your optimism is contagious.",
  "You're incredibly hardworking.",
  "Your loyalty.",
  "You make me feel appreciated.",
  "Your laugh is infectious.",
  "You make me a better person.",
  "Your sense of adventure.",
  "You're always there when I need you.",
  "Your passion for life.",
  "The way you hold my hand.",
  "You're an amazing listener.",
  "Your generosity.",
  "You respect me.",
  "You're honest with me.",
  "You're my rock.",
  "You make me feel cherished.",
  "Your kisses are magical.",
  "You're my favorite person.",
  "Your resilience.",
  "You're my partner in crime.",
  "Your strength.",
  "You make me feel alive.",
  "Your dedication to our relationship.",
  "You're always honest with me.",
  "Your warm heart.",
  "You make everyday brighter.",
  "Your sense of style.",
  "You're my soulmate.",
  "Your sense of adventure.",
  "You always have the best ideas.",
  "You're my inspiration.",
  "You understand me.",
  "You make me feel special.",
  "Your positive attitude.",
  "You're so caring.",
  "You're my comfort.",
  "Your smile is contagious.",
  "You're my partner in everything.",
  "Your laugh makes me happy.",
  "You're my safe haven.",
  "Your spontaneity.",
  "You make me feel loved.",
  "You're incredibly thoughtful.",
  "You always make time for me.",
  "You're my favorite person to talk to.",
  "You make me feel important.",
  "Your loyalty means the world to me.",
  "You're my best friend and lover.",
  "You're my constant support.",
  "Your warmth.",
  "You make me feel understood.",
  "You're my perfect match.",
  "Your patience with me.",
  "You're my biggest fan.",
  "You make me laugh like no one else.",
  "Your loving nature.",
  "You make life fun.",
  "You're always there for me.",
  "Your thoughtfulness.",
  "You make my heart skip a beat.",
  "You're my everything.",
  "Your encouragement.",
  "You're my greatest adventure.",
  "You make me feel at home.",
  "Your tenderness.",
  "You make me smile.",
  "Your dedication to us.",
  "You're my forever.",
  "You make life worth living.",
  "You're my reason to smile.",
  "You make me feel complete.",
  "Your love is my strength.",
  "You're my one and only.",
  "I LOVE YOU ♡",
];

export default reasons;